const projectData = [
  {
    id: 1,
    name: "Harisenin Final Project",
    time: "Aug 2023 - Dec 2023",
    link: "",
    repo: "https://github.com/agungardneham/final-project-harisenin",
    shortDesc:
      "I lead this team project to graduate from Harisenin's Bootcamp. This project is about building the frontend and backend of a restaurant delivery website app.",
    task: [
      "Lead a team of 8 man to build a fullstack web application",
      "Lead the weekly meeting and report the progress",
      "Find a template for a proper restaurant delivery website app",
      "Designed and determined the color palette and typography",
      "Designed the layout and logo of the website using Figma",
      "Transform Figma design to code",
      "Lead the github workflow and revising the code",
      "Developed the frontend using ReactJS and Tailwind CSS",
      "Make sure the website is responsive",
    ],
    tool: [
      "ReactJS",
      "TailwindCSS",
      "Balsamiq",
      "Figma",
      "Github",
      "Git",
      "ViteJS",
      "Vercel",
      "Javascript",
      "CSS",
      "HTML",
    ],
    image: [
      "/resources/finalProject1.png",
      "/resources/finalProject2.png",
      "/resources/finalProject3.png",
      "/resources/finalProject4.png",
    ],
  },
  {
    id: 2,
    name: "Portfolio Website Project (Version 2)",
    time: "Aug 2023 - Sep 2023",
    link: "/",
    repo: "https://github.com/agungardneham/portfolio-v2",
    shortDesc:
      "Website project for my personal portfolio. Mainly uses ReactJS and Tailwind CSS.",
    task: [
      "Transform given Figma design to code",
      "Developed the frontend using ReactJS, TailwindCSS, and Bootstrap",
      "Developed the logic and interactivity of the website",
      "Make sure the website is responsive",
    ],
    tool: [
      "ReactJS",
      "TailwindCSS",
      "Bootstrap",
      "ViteJS",
      "Vercel",
      "Github",
      "Git",
      "Javascript",
      "CSS",
      "HTML",
    ],
    image: [
      "/resources/portfoliov2-1.png",
      "/resources/portfoliov2-2.png",
      "/resources/portfoliov2-3.png",
      "/resources/portfoliov2-4.png",
      "/resources/portfoliov2-5.png",
      "/resources/portfoliov2-6.png",
    ],
  },
  {
    id: 3,
    name: "Metalfest ITB 2022",
    time: "Jul 2021- Feb 2022",
    link: "http://www.metalfestitb.com",
    repo: "",
    repoClass: "hidden",
    shortDesc:
      "Website project for Metalfest ITB events. The main feature is to provide information and registration for the event.",
    task: [
      "Lead a team of 5 man to create a website for registering and providing information of the event",
      "Find the best method to develop the website for my team",
      "Determined the template and layout for the website page",
      "Did a front end development for the website",
      "Coordinated with other department to make a good UI/UX design and livestream layout",
    ],
    tool: ["HTML", "CSS", "Javascript", "Wordpress"],
    image: [
      "/resources/metalfest1.png",
      "/resources/metalfest2.png",
      "/resources/metalfest3.png",
      "/resources/metalfest4.png",
      "/resources/metalfest5.png",
    ],
  },
  {
    id: 4,
    name: "Portfolio Website Project",
    time: "May 2023 - Jun 2023",
    link: "https://agungardneham.github.io/portfolio/",
    repo: "https://github.com/agungardneham/portfolio",
    shortDesc: "My first portfolio project that mainly uses bootstrap.",
    task: [
      "Designed the layout and style of the website",
      "Wrote the content of the website",
    ],
    tool: ["HTML", "CSS", "Javascript", "Bootstrap", "Git", "Github"],
    image: [
      "/resources/portfolio1.png",
      "/resources/portfolio2.png",
      "/resources/portfolio3.png",
      "/resources/portfolio4.png",
      "/resources/portfolio5.png",
    ],
  },
  {
    id: 5,
    name: "RevoU Software Engineering Mini Course Final Project",
    time: "Mar 2023",
    link: "https://agungardneham.github.io/portfolio/revou.html",
    repo: "https://github.com/agungardneham/mini-coding-project-revou",
    shortDesc:
      "This is an introduction course to web development. In this course's final project, I must use vanilla HTML, CSS, and JS.",
    task: [
      "Transform given website design into code",
      "Developed the frontend using vanilla HTML, CSS, and Javascript",
      "Developed the logic and interactivity of the website",
    ],
    tool: ["HTML", "CSS", "Javascript", "Github"],
    image: [
      "/resources/revou1.png",
      "/resources/revou2.png",
      "/resources/revou3.png",
      "/resources/revou4.png",
    ],
  },
  // {
  //   id: 6,
  //   name: "Mini Games Project",
  //   time: "May 2023 - Jul 2023",
  //   link: "",
  //   repo: "",
  //   shortDesc: "Mini games project to train my logic at javascript,",
  // },
];

export default projectData;
